### ISSUE TITLE
非流的返回格式比openai标准的多了不少东西

### ISSUE THREAD

**Issue by andrewcapture** [Star-Studio-Develop/Groq2API#26]
有个bug，非流的返回格式比openai标准的多了不少东西，导致一些按openai标准的问答程序报错

**Comment by MagicalMadoka** [comment]
多了什么？什么问答程序？

**Comment by andrewcapture** [comment]
> 多了什么？什么问答程序？

chatNextWeb报错
{
  "error": true,
  "message": "empty response from server"
}

**Comment by MagicalMadoka** [comment]
没有得到确切的回复先关了
