### ISSUE TITLE
报错400了，前几天正常

### ISSUE THREAD

**Issue by yonflee2025** [Star-Studio-Develop/Groq2API#30]
ega.ega.POST /v1/chat/completions HTTP/1.1
User-Agent: curl/7.29.0
Host: 127.0.0.1:8003
Accept: */*
Authorization: Bearer ATaFeZFta5-5VeGxPeCRcIX-tNWZdVknOdZZVdI0vJnO
Content-Length: 129
Content-Type: application/x-www-form-urlencoded

{
  "messages": [
    {
      "role": "user",
      "content": "hi"
    }
  ],
  "model": "llama3-8b-8192",
  "max_tokens": 500
}
01:12:04.779419 IP (tos 0x0, ttl 64, id 16995, offset 0, flags [DF], proto TCP (6), length 52)
    172.17.0.12.8080 > 172.17.0.1.54752: Flags [.], cksum 0x5856 (incorrect -> 0x6181), seq 1, ack 366, win 59, options [nop,nop,TS val 1701274041 ecr 1701274041], length 0
E..4Bc@.@..1............:Z#.N..H...;XV.....
ega.ega.
01:12:05.263781 IP (tos 0x0, ttl 64, id 16996, offset 0, flags [DF], proto TCP (6), length 325)
    172.17.0.12.8080 > 172.17.0.1.54752: Flags [P.], cksum 0x5967 (incorrect -> 0x0ac9), seq 1:274, ack 366, win 59, options [nop,nop,TS val 1701274526 ecr 1701274041], length 273: HTTP, length: 273
	HTTP/1.1 400 Bad Request
	Access-Control-Allow-Headers: *
	Access-Control-Allow-Methods: *
	Access-Control-Allow-Origin: *
	Content-Type: application/json; charset=utf-8
	Date: Wed, 24 Apr 2024 01:12:05 GMT
	Content-Length: 43
	
	{"error":"response status code is not 200"}[!http]

**Comment by chandlergis** [comment]
被封了估计
